### ISSUE TITLE
绑定SessionToken时出现未知报错

### ISSUE THREAD

**Issue by SALTWOOD** [Catrong/phi-plugin#10]
![新建位图图像](https://github.com/Catrong/phi-plugin/assets/105980161/f5816af3-7f62-4ff6-81ae-59a43d3c1cc4)
在使用/phi bind时出现错误

**Comment by Catrong** [comment]
这个是重复存档，我也不知道触发原因（（目前想到的解决方式是直接选择第一个存档（但是还没写，因为作者这两天要期末考试）准备考完后解决这个问题。如果可以的话，希望可以联系我提供一些sstk（当然不提供也可以）谢谢！

**Comment by Catrong** [comment]
已经暂时解决，如果有问题还望反馈
