### ISSUE TITLE
无法获取帮助图片

### ISSUE THREAD

**Issue by ABKQPO** [Catrong/phi-plugin#105]
[TRSSYz][00:11:03.149][MARK] [phi-help][help] #phi help 处理完成 2ms
[TRSSYz][00:11:03.177][ERRO] ApiRejection { code: -60, message: 'empty message' }

**Comment by Catrong** [comment]
查看一下 /resources/html/otherimg/ 目录下有没有一个 help.png，如果没有的话请尝试更新一下插件或者重新安装

**Comment by ABKQPO** [comment]
有图片但是仍然为空

**Comment by Catrong** [comment]
新的版本可能解决了这个问题嗷，请问现在可以正常使用了嘛

**Comment by ABKQPO** [comment]
可以了
