### ISSUE TITLE
micans指令失效，mic提示指令无响应

### ISSUE THREAD

**Issue by ABKQPO** [Catrong/phi-plugin#108]
[TRSSYz][22:29:53.968][MARK] [phi-guessMic][ans] /micans
[TRSSYz][22:29:53.968][ERRO] [phi-guessMic][ans]
[TRSSYz][22:29:53.969][ERRO] undefined

**Comment by Catrong** [comment]
/mic 指令还在试验阶段嗷，目前并没有找到合适的方法适配频道，所以可能会有些问题嗷（比如随机到没有乐曲资源的曲目等），还望谅解
