### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jiasswee** [Catrong/phi-plugin#111]
[TRSSYz][12:58:24.662][INFO] ------φ^_^φ------
[TRSSYz][12:58:26.255][INFO] [Phi-Plugin]导入新版puppteer
[TRSSYz][12:58:26.870][ERRO] linux
[TRSSYz][12:58:26.871][INFO] [Phi-Plugin][re8] 导入 unix? 模块
Segmentation fault
~/Yunzai #

**Comment by Catrong** [comment]
新的版本可能修复了这些问题，请问现在可以正常使用了嘛
