### ISSUE TITLE
背景图没了，重装过也不行

### ISSUE THREAD

**Issue by Huamos** [Catrong/phi-plugin#114]
![QQ图片20240117150824](https://github.com/Catrong/phi-plugin/assets/100054204/80ebe2a2-4e4b-4fd2-8523-273782d640a9)
![QQ图片20240117150829](https://github.com/Catrong/phi-plugin/assets/100054204/259a6c11-7f1c-4357-adbf-94416fdfdadb)

**Comment by Catrong** [comment]
输入 #phi下载曲绘 试试
