### ISSUE TITLE
发送图片无法加载（？）

### ISSUE THREAD

**Issue by youyi0218** [Catrong/phi-plugin#116]
![image](https://github.com/Catrong/phi-plugin/assets/135406843/93e12e10-bfb5-4f34-bb0a-7d44caf99b89)
qu'hui曲绘加载不全
![image](https://github.com/Catrong/phi-plugin/assets/135406843/7bdf8019-38ae-41ec-a378-1e4eb20f93bc)
猜曲图片无法加载
![image](https://github.com/Catrong/phi-plugin/assets/135406843/b970d039-6db9-4e4d-8441-01debbd2d935)
![image](https://github.com/Catrong/phi-plugin/assets/135406843/510da46b-3619-49b1-9855-cd68a994f40a)
![image](https://github.com/Catrong/phi-plugin/assets/135406843/3ce6d034-5c94-42f0-b426-7865d8abea28)
![image](https://github.com/Catrong/phi-plugin/assets/135406843/4a7d73b2-b65d-4d50-9f2c-2ea02a9c8910)
![image](https://github.com/Catrong/phi-plugin/assets/135406843/185dbbe8-2d20-481c-ae28-ef4640a587a8)

**Comment by Catrong** [comment]
目前获取曲绘是通过gitee哦！如果觉得速度太慢可以使用`#下载曲绘`来把曲绘缓存到本地嗷！
