### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by 112121212167987534524** [Catrong/phi-plugin#12]
![image](https://github.com/Catrong/phi-plugin/assets/117198625/1de3c2ca-d57c-47b9-b0fc-ee181269bcdf)
![image](https://github.com/Catrong/phi-plugin/assets/117198625/d218c5bf-2b78-466b-8b5f-67c9ccd35356)

**Comment by Catrong** [comment]
唔，更新了嘛

**Comment by 112121212167987534524** [comment]
![image](https://github.com/Catrong/phi-plugin/assets/117198625/96771926-9d7b-4bdc-9e26-03713d4d9a42)

**Comment by 112121212167987534524** [comment]
最新版本了

**Comment by Catrong** [comment]
唔唔，我再看看，好像知道哪里的问题了

**Comment by Catrong** [comment]
更新试试
