### ISSUE TITLE
更新只能强制更新吗

### ISSUE THREAD

**Issue by youyi0218** [Catrong/phi-plugin#121]
使用#phi更新报错
更新失败！存在冲突：
Error: Command failed: git -C ./plugins/phi-plugin/ pull --no-rebase
error: Your local changes to the following files would be overwritten by merge:
	README.md
	apps/session.js
	apps/user.js
	lib/PhigrosLibrary_linux.node
	model/getdata.js
	resources/info/nicklist.yaml
Please commit your changes or stash them before you merge.
Aborting

请解决冲突后再更新，或者执行#强制更新，放弃本地修改
只能强制更新吗，强制更新本地绑定的用户数据会不会消失？

**Comment by Catrong** [comment]
强制更新不会改变data目录嗷，但是所有设置以及自定义别名曲目等将可能会重置。如果不放心的话，可以把项目下载下来然后覆盖到本地嗷
