### ISSUE TITLE
更新成绩时报错了（

### ISSUE THREAD

**Issue by KeluIsAfkeru** [Catrong/phi-plugin#126]
![image](https://github.com/Catrong/phi-plugin/assets/107661829/eabe32d0-1c8c-4742-bd89-ebea37a43bcd)

**Comment by KeluIsAfkeru** [comment]
憋憋，更新最新版trss导致的，回退到旧版恢复了（）

**Comment by RinLin-NYA** [comment]
> > 憋憋，更新最新版trss导致的，回退到旧版恢复了（）
> 
> 看看版本

TRSS-Yunzai v3.1.3 导致 phi-plugin 出现问题的版本应该不会晚于这个版本
如果更详细一点说，[db394ca](https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec)以后的版本会导致 phi-plugin 不能正确处理数据

**Comment by S-t-e-v-e-e** [comment]
> > > 憋憋，更新最新版trss导致的，回退到旧版恢复了（）
> > 
> > 
> > 看看版本
> 
> TRSS-Yunzai v3.1.3 导致 phi-plugin 出现问题的版本应该不会晚于这个版本 如果更详细一点说，[db394ca](https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec)以后的版本会导致 phi-plugin 不能正确处理数据

![image](https://github.com/Catrong/phi-plugin/assets/117198625/cf7132f0-e2de-488a-9cfd-0b44d91f6468)

**Comment by KeluIsAfkeru** [comment]
> > > > 憋憋，更新最新版trss导致的，回退到旧版恢复了（）
> > > 
> > > 
> > > 看看版本
> > 
> > 
> > TRSS-Yunzai v3.1.3 导致 phi-plugin 出现问题的版本应该不会晚于这个版本 如果更详细一点说，[db394ca](https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec)以后的版本会导致 phi-plugin 不能正确处理数据
> 
> ![image](https://private-user-images.githubusercontent.com/117198625/316247292-cf7132f0-e2de-488a-9cfd-0b44d91f6468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDU0NDAsIm5iZiI6MTcxMTIwNTE0MCwicGF0aCI6Ii8xMTcxOTg2MjUvMzE2MjQ3MjkyLWNmNzEzMmYwLWUyZGUtNDg4YS05Y2ZkLTBiNDRkOTFmNjQ2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNDQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGU0MTUwNWY5ODJjOGYxY2QzMjIyODQ1NDFiYjc3OTJjZjRkMDBmMDIxYTk0NDBmZDNjODNkOWMwMmM0ZGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l2lY8BWeB-r_5FCbzzrpBUxO5W4NNFWYsSaFOZ0L7Hk)


 #nodejs用的20.11.1也报错，自从[https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec](url)这个提交把node-fetch版本从3.3.2换掉就出问题了

**Comment by RinLin-NYA** [comment]
> > > > 憋憋，更新最新版trss导致的，回退到旧版恢复了（）
> > > 
> > > 
> > > 看看版本
> > 
> > 
> > TRSS-Yunzai v3.1.3 导致 phi-plugin 出现问题的版本应该不会晚于这个版本 如果更详细一点说，[db394ca](https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec)以后的版本会导致 phi-plugin 不能正确处理数据
> 
> ![image](https://private-user-images.githubusercontent.com/117198625/316247292-cf7132f0-e2de-488a-9cfd-0b44d91f6468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDkxMDcsIm5iZiI6MTcxMTIwODgwNywicGF0aCI6Ii8xMTcxOTg2MjUvMzE2MjQ3MjkyLWNmNzEzMmYwLWUyZGUtNDg4YS05Y2ZkLTBiNDRkOTFmNjQ2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxNTQ2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWE1Njc1MDE1YWZkYzA0ODljOTM4MzMyMWZlODAyYWM1NjVmMjEyZWU2NDIyYmI4MTljMWI1ODUyYzM1NTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-2HLzNdD8uhtOzmMsN4zsvpCok1bGwZ2Fr2VDEulz6E)

目前在使用 Node v21.6.2
