### ISSUE TITLE
Phi-Plugin 的存档绑定与成绩更新问题

### ISSUE THREAD

**Issue by RinLin-NYA** [Catrong/phi-plugin#129]
在 TRSS-Yunzai 的 [db394ca](https://github.com/TimeRainStarSky/Yunzai/commit/db394ca6037d4bece8e772202dc33c941d412aec) 更新以后，Phi-Plugin 就无法正常绑定和更新数据，输出报错如下：

>
>TypeError: Dictionary:  is not an accepted type. Expected one of navigate, same-origin, no-cors, cors.
>

这一问题在 #126 中已有反馈，在和 TRSS-Yunzai 方面沟通后，TRSS-Yunzai 方面提供了 [这个方案](https://github.com/TimeRainStarSky/Yunzai/issues/82) 用于临时过渡，~~但采用此方式后新的报错如下：~~

>
>~~RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be an integer. Received NaN~~
>

好吧是咱存档太陈旧了(

目前已知问题出自 node-fetch，所以各位打算什么时候适配新版本(

**Comment by Catrong** [comment]
收到，感谢

**Comment by RinLin-NYA** [comment]
发现问题解决了都不关issue的屑铃萤.png
