### ISSUE TITLE
[Enhancement] 接入taptap實現一鍵登錄

### ISSUE THREAD

**Issue by yt6983138** [Catrong/phi-plugin#130]
見標題, 想請問作者有沒有打算接入taptap api來達成一鍵登錄(找token對小白不友好), 最近研究出來如何接入taptap api 了, 奈何不會寫js, 沒辦法開pull request(

具體的實現在[這裏](https://github.com/yt6983138/PhigrosLibraryCSharp/tree/master/Cloud/Login), 語言是c#, 大概流程:
1. 獲取QRCode
2. 等待用戶登入, 在這期間需要每隔幾秒發送請求直到用戶登入完畢
3. 獲取登入資料以及用戶profile
4. 在phigros 的lc 服務器登入
5. 拿到token 后同/bind指令後續

**Comment by KeluIsAfkeru** [comment]
这个方式好像大陆地区内无法使用？）
![image](https://github.com/Catrong/phi-plugin/assets/107661829/3aa8c83c-57af-426d-b10a-bd6c5cf0c302)
![f2846583bc711f6b12c36a87b9f8353a](https://github.com/Catrong/phi-plugin/assets/107661829/2115c847-8cdb-4740-a0f3-e65106206fc1)

**Comment by yt6983138** [comment]
> 这个方式好像大陆地区内无法使用？）
我測試是可以欸, 我用大陸的注冊, 在 `RequestLoginQrCode()`那一行, 有一個可選parameter `useChinaEndpoint` 設爲true 則使用大陸的api登入

**Comment by KeluIsAfkeru** [comment]
> > 这个方式好像大陆地区内无法使用？）
> 
> 我測試是可以欸, 我用大陸的注冊, 在 `RequestLoginQrCode()`那一行, 有一個可選parameter `useChinaEndpoint` 設爲true 則使用大陸的api登入

好的谢谢你，我去试试qwq

**Comment by yt6983138** [comment]
順帶一提, 有些method也會有`useChinaEndpoint `這個parameter, 要注意一下

**Comment by KeluIsAfkeru** [comment]
> 順帶一提, 有些method也會有`useChinaEndpoint `這個parameter, 要注意一下

成功了，很棒很有意义，现在就算是小白也能轻松无障碍拿到token啦，希望作者早日适配
![image](https://github.com/Catrong/phi-plugin/assets/107661829/379ffa4f-5036-4a53-8505-27c77db2680d)

**Comment by Dnyo666** [comment]
废酱可能高考完了得等一段时间弄这个吧

**Comment by yt6983138** [comment]
順帶一提哈 部分api有更新 useChinaEndpoint已經全部移除

**Comment by yt6983138** [comment]
目前我想到的方法(不手動翻譯的情況下)是將我的庫編譯成wasm文件然後在node js裡invoke, 但是得再研究研究

**Comment by Catrong** [comment]
已实现，感谢！
