### ISSUE TITLE
图片渲染异常

### ISSUE THREAD

**Issue by riluoya** [Catrong/phi-plugin#135]
总是会有部分曲绘渲染不出来，渲染一半的问题
渲染图片如下：
![Image_1721026823031](https://github.com/user-attachments/assets/ee666bfb-acf3-4c19-8ec5-181182889f74)

插件渲染设置如下：
![Screenshot_2024-07-15-15-02-01-695_mark via](https://github.com/user-attachments/assets/55a5ae9e-d0a3-4972-9f89-4f3544f9c2ce)

**Comment by riluoya** [comment]
更新一下曲库罢（）

**Comment by Catrong** [comment]
曲绘需要手动更新嗷
/下载曲绘

**Comment by riluoya** [comment]
好的，谢谢
