### ISSUE TITLE
又又报错了

### ISSUE THREAD

**Issue by 112121212167987534524** [Catrong/phi-plugin#14]
![image](https://github.com/Catrong/phi-plugin/assets/117198625/f54ebcab-1b79-4a1d-bd03-566067beec1b)

**Comment by Catrong** [comment]
是更新后的代码吗，这个报错的行数有些不对啊

**Comment by 112121212167987534524** [comment]
![e8a2a96e458a56366fd2e9aaec0ddd58_720](https://github.com/Catrong/phi-plugin/assets/117198625/be6895df-0e36-480a-a27e-1d1a3fb36dc8)

**Comment by Catrong** [comment]
试试#phi强制更新

**Comment by 112121212167987534524** [comment]
![662aac8a92a452255278aafeed274410](https://github.com/Catrong/phi-plugin/assets/117198625/f757bc70-7f85-42a9-9feb-3fc95a14196c)

**Comment by 112121212167987534524** [comment]
没用
