### ISSUE TITLE
渲染精度位置

### ISSUE THREAD

**Issue by riluoya** [Catrong/phi-plugin#144]
请问渲染精度位置在那里，锅巴我用不了了（）
希望可以告知一下配置文件的位置，谢谢~

**Comment by Catrong** [comment]
配置文件在`phi-plugin/config/config/config.yaml`
如果是早期开始使用插件的话部分设置项可能没有注释，可以对照`phi-plugin/config/default_config/config.yaml`的注释进行修改（请不要修改默认配置）

**Comment by riluoya** [comment]
好的谢谢
