### ISSUE TITLE
麻烦废有空看一下反馈表单呐

### ISSUE THREAD

**Issue by MYS-KISO** [Catrong/phi-plugin#151]
![Screenshot_20240927_000017](https://github.com/user-attachments/assets/af27bc49-a0b5-4e38-8edb-ea47da9cc49a)
[工作日卸了QQ嘛 想不到什么其他方法联系废了QAQ，抱歉占据了一个issue]

**Comment by Catrong** [comment]
感谢滢酱呐！
（其实也可以直接发我邮箱的说

**Comment by MYS-KISO** [comment]
您好qw~这是一条来自PRy_OS的自动回复，您的邮件已经成功丢入润滢百年不看的收件箱了(大雾)谢谢您的来信~MYS-KISO//PRy_OS

**Comment by MYS-KISO** [comment]
> 您好qw~这是一条来自PRy_OS的自动回复，您的邮件已经成功丢入润滢百年不看的收件箱了(大雾)谢谢您的来信~MYS-KISO//PRy_OS

蛤 这个原来可以通过邮件发的嘛
