### ISSUE TITLE
推分建议报错

### ISSUE THREAD

**Issue by vaodj** [Catrong/phi-plugin#16]
![Snipaste_2023-07-12_20-22-29](https://github.com/Catrong/phi-plugin/assets/90913120/5ab5f917-407c-4319-b4df-711297a3fa04)

**Comment by Catrong** [comment]
更新一下试试

**Comment by vaodj** [comment]
依然报错（
![Snipaste_2023-07-13_09-17-32](https://github.com/Catrong/phi-plugin/assets/90913120/b5dab312-1e24-4627-9673-1be1669b00ba)

**Comment by Catrong** [comment]
可以看一下具体报错行数吗

**Comment by vaodj** [comment]
好像就是这样的，连个报错行数都没有（

**Comment by 112121212167987534524** [comment]
> 好像就是这样的，连个报错行数都没有（

重新绑定
