### ISSUE TITLE
#rks报错

### ISSUE THREAD

**Issue by WindraiteLesd** [Catrong/phi-plugin#2]
已经录入数据的用户在bot重启后输入#rks会报错，上次似乎是录一半没录完的时候重启了，手动结束就恢复了，但这次手动结束也没作用。没有录数据的不会报错，
另外“Non-Melodic Ragez”，“Another Me”这两首似乎无法正常录入
![IMG_20230227_002014](https://user-images.githubusercontent.com/104503043/221422774-69165ff3-9630-485a-8459-a7eb3422e599.jpg)

**Comment by Catrong** [comment]
可以更新之后再试一下，现在应该可以读入 Another Me 了，但是暂时没有找到为什么读不了 Non-Melodic Ragez(MUG Edit) 。因为学习原因，我会在周末去详细测试这个问题，当然如果还有报错也可以先在这里发出来，谢谢

**Comment by WindraiteLesd** [comment]
> 可以更新之后再试一下，现在应该可以读入 Another Me 了，但是暂时没有找到为什么读不了 Non-Melodic Ragez(MUG Edit) 。因为学习原因，我会在周末去详细测试这个问题，当然如果还有报错也可以先在这里发出来，谢谢
语法错误？
```
载入插件错误：phirks
SyntaxError: Unexpected token '{'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:68:21)

```

**Comment by Catrong** [comment]
晕，半夜在寝室用手机写的，没看清少了个括号

**Comment by WindraiteLesd** [comment]
> 可以更新之后再试一下，现在应该可以读入 Another Me 了，但是暂时没有找到为什么读不了 Non-Melodic Ragez(MUG Edit) 。因为学习原因，我会在周末去详细测试这个问题，当然如果还有报错也可以先在这里发出来，谢谢

这个发现了，是因为括号前面带空格会识别不了

**Comment by WindraiteLesd** [comment]
今天汇总的一些问题
1.data里的数据莫名其妙会全部归零
2.录FULi AUTO BUSTER的数据会变成FULi AUTO SHOOTER
3.部分曲绘丢失(这个也可能是我的网络问题)

可能的问题
数据被清空后录数据会按照全曲目顺序来，只能暂停后再使用#rksacc来指定曲目录入

**Comment by WindraiteLesd** [comment]
phirks.js底部的footer is not defined导致了无法加载插件

**Comment by WindraiteLesd** [comment]
[phi插件][showconfig].yaml 读取失败 Error: ENOENT: no such file or directory, open 'C:/Users/Administrator/Desktop/Yunzai-Bot/plugins/phi-plugin/config/default/showconfig.yaml'
