### ISSUE TITLE
希望可以做个猜歌功能

### ISSUE THREAD

**Issue by Walkersifolia** [Catrong/phi-plugin#85]
和猜曲绘类似，随机选某首歌的某个片段（资源已经弄好了），然后一段时间猜不出来，放同一首歌的另一个片段，片段都用数字序号编好了，代码部分感觉改改猜曲绘的就行（），资源再想办法，获取放到我服务器上是个可行的方案，无论是url还是链接下载

**Comment by Catrong** [comment]
感谢！
