### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by Lovehutao520** [Catrong/phi-plugin#98]
![Screenshot_2023-10-22-12-59-47-96_84d3000e3f4017145260f7618db1d683](https://github.com/Catrong/phi-plugin/assets/121493510/9aede5a4-a04e-477e-9baf-6a2a00775f3a)
这是怎么回事，然后不知道是我指令错了还是什么，绑定没反应，ill获取图片也只是有显示反应但是qq前台不发图没反应

**Comment by Catrong** [comment]
是最新版吗，重新安装下依赖试试，re8没有加载上的话可以说一下你的系统版本，绑定和ill的问题发一下日志（

**Comment by 7aGiven** [comment]
建议更新到最新再试试。

**Comment by Lovehutao520** [comment]
弄好了，删了重装了一次，虽然re还是没好但是能用了
